### ISSUE TITLE
Oembed now fails

### ISSUE THREAD

**Issue by JONBRWN** [Instagram/instagram-ruby-gem#162]
running `Instagram.oembed('http://instagr.am/p/fA9uwTtkSN/')`
brings up `JSON::ParserError: 757: unexpected token at` followed by HTML.

Stack trace: 

```
  from /Users/.rvm/gems/ruby-2.0.0-p481/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
  from /Users/.rvm/gems/ruby-2.0.0-p481/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
  from /Users/.rvm/gems/ruby-2.0.0-p481/gems/instagram-1.1.3/lib/faraday/raise_http_exception.rb:43:in `error_body'
  from /Users/.rvm/gems/ruby-2.0.0-p481/gems/instagram-1.1.3/lib/faraday/raise_http_exception.rb:36:in `error_message_400'
  from /Users/.rvm/gems/ruby-2.0.0-p481/gems/instagram-1.1.3/lib/faraday/raise_http_exception.rb:13:in `block in call'
  from /Users/.rvm/gems/ruby-2.0.0-p481/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
  from /Users/.rvm/gems/ruby-2.0.0-p481/gems/instagram-1.1.3/lib/faraday/raise_http_exception.rb:8:in `call'
  from /Users/.rvm/gems/ruby-2.0.0-p481/gems/faraday_middleware-0.9.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
  from /Users/.rvm/gems/ruby-2.0.0-p481/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
  from /Users/.rvm/gems/ruby-2.0.0-p481/gems/faraday-0.9.1/lib/faraday/request/url_encoded.rb:15:in `call'
  from /Users/.rvm/gems/ruby-2.0.0-p481/gems/instagram-1.1.3/lib/faraday/oauth2.rb:33:in `call'
  from /Users/.rvm/gems/ruby-2.0.0-p481/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
  from /Users/.rvm/gems/ruby-2.0.0-p481/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
  from /Users/.rvm/gems/ruby-2.0.0-p481/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
  from /Users/.rvm/gems/ruby-2.0.0-p481/gems/instagram-1.1.3/lib/instagram/request.rb:31:in `request'
  from /Users/.rvm/gems/ruby-2.0.0-p481/gems/instagram-1.1.3/lib/instagram/request.rb:9:in `get'
  from /Users/.rvm/gems/ruby-2.0.0-p481/gems/instagram-1.1.3/lib/instagram/client/embedding.rb:24:in `oembed'
  from /Users/.rvm/gems/ruby-2.0.0-p481/gems/instagram-1.1.3/lib/instagram.rb:20:in `method_missing
```
I have a fix in place but could use some help with configuring the tests to work with it

**Comment by jGRUBBS** [comment]
#163 needs to be merged. This definitely solves the issue for me.

**Comment by facebook-github-bot-1** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
